services:
  osrm:
    image: osrm/osrm-backend
    container_name: osrm-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./docker/osrm:/data
    command: osrm-routed --algorithm mld /data/mexico-latest.osrm
